### ISSUE TITLE
Find attractors and their basins

### ISSUE THREAD

**Issue by kyuhyongpark** [kyuhyongpark/cubewalkers-analysis#1]
Write a python script that finds the attractors and their basins of the models in the Cell Collective and store them in a csv format.
Need a check to make sure all the oscillating nodes in a complex attractor do oscillate within the sampling time.

Optional:
- [ ] sort attractors by the source node values
- [ ] find attractors in the asynchronous update using pystablemotifs
- [ ] find node average values and sort the nodes
- [ ] identify common attractors in the synchronous and the asynchronous update

**Comment by jcrozum** [comment]
If we decide to do this more in-depth attractor analysis, it will be as part of a separate project, so I'm closing this here.
