### ISSUE TITLE
Improve readme

### ISSUE THREAD

**Issue by jcrozum** [kyuhyongpark/cubewalkers-analysis#21]
We should make the readme file a bit more clear, i.e., give a brief description of what someone would have to run here to reproduce the results of the PRX Life paper.

**Comment by kyuhyongpark** [comment]
@jcrozum Should I also try to update `requirements.txt`? It is not hard to update it, but it will be a bit tricky for people to install all of them, and some of the libraries are used for a single notebook. Current list is

`cubewalkers`
`cupy` which also requires CUDA
`pystablemotifs`
`pyboolnet`
`matplotlib`
`pandas`
`cana`
`numpy`
`scipy`

**Comment by jcrozum** [comment]
Yes, just update it, but I would take `cupy` off the list and make a note in the readme saying that it's required but can't be automatically installed (because you need the right version for your hardware).
