### ISSUE TITLE
Organize scripts, results, and notebook for the reviewers

### ISSUE THREAD

**Issue by kyuhyongpark** [kyuhyongpark/cubewalkers-analysis#6]
We want to organize our current results in the following manner:
1. Python scripts that produce the results and their output data in csv format
- [x] Node average values in sync/async update
- [x] Derrida coefficients in sync/async, with/out source perturbation
- [x] Hamming distance in time in sync/async, with/out source perturbation
- [x] Quasicoherence, Fuzzy quasicoherence, and final Hamming distance in sync/async, with/out source perturbation
- [ ] Quasi-attractors
- [x] Standard deviation of node average values depending on the number of walkers
2. Jupyter notebook that collects the above data and creates plots and tables.
- [x] Analysis of specific models
- [x] Node average values and their standard deviation
- [x] Hamming distance in time plots
- [x] perturbation output analysis

I'm sure there's more to be added to the list. Let me know, and I'll add it here. Even if we don't add everything here, that's still fine.

**Comment by jcrozum** [comment]
The paper has been accepted
